### ISSUE TITLE
Update model_args.json name to config.json

### ISSUE THREAD

**Issue by KimballNJardine** [DRAGNLabs/301r_retnet#16]
Drew has pointed out that HuggingFace is looking for a config.json file. Our equivalent is named model_args.json. We may want to update the name of the json file output, or create a separate json file called config.json that holds all parameters (maybe not just defaults, but to be determined) to be used for generating a model for inference.

**Comment by nprisbrey** [comment]
Seems like a good idea. Does the config.json file not allow including any of the values we originally wanted to keep track of?

**Comment by nprisbrey** [comment]
Is this issue being addressed at all in the [hugging_faceify](https://github.com/DRAGNLabs/301r_retnet/tree/hugging_faceify) branch @jeffeardley?
