### ISSUE TITLE
Standardize name of validation objects.

### ISSUE THREAD

**Issue by KimballNJardine** [DRAGNLabs/301r_retnet#19]
In train_model.py, we have val_freq, a variable tracking how many times we want to do validation per epoch. We also have other variables like val_predictions, val_loss, val_total_loss, and val_total_samples (This list is not necessarily exhaustive).
In load_data.py, we have valid_loader, a DataLoader object for validation.
We use valid_loader named as valid_loader in train_model.py.

If we can standardize the shorthand for validation, either to val or valid that would be nice.

**Comment by nprisbrey** [comment]
Just as a note, this could end up being addressed with the PRs today and tomorrow due to our efforts (starting with PR #22) to replace `load_data.py` entirely.

**Comment by nprisbrey** [comment]
@KimballNJardine, can this now be considered resolved?
