### ISSUE TITLE
Non-standardized form for parser arguments.

### ISSUE THREAD

**Issue by KimballNJardine** [DRAGNLabs/301r_retnet#27]
This will probably be made irrelevant by the YAML branch. However, there are two different styles for parser args. See train_model.py, and tokenize_data.py for example.
Examples:
train_model.py: 
    parser.add_argument("--dataset-subset", type=str, default="wikitext-2-v1",
        help="Subset/config to use for Hugging Face dataset.")
tokenize_data.py for example:
    parser.add_argument(
        "--tokenized_data_name",
        type=str,
        required=True,
        help="Name of tokenized data.")

**Comment by nprisbrey** [comment]
@KimballNJardine, has this now been resolved after #29?

**Comment by nprisbrey** [comment]
Since all parser arguments have been dropped as of [f91cca2](https://github.com/DRAGNLabs/301r_retnet/pull/30/commits/f91cca25d92c350f3608be523ce73ffac0aefb8c), I'm considering this resolved.
