### ISSUE TITLE
Save training configuration alongside checkpoints/logs

### ISSUE THREAD

**Issue by JayOrten** [DRAGNLabs/301r_retnet#51]
Training configuration parameters, from the YAML file, are printed out in the .out file. However, we should also save these parameters in a separate file, alongside the run checkpoints and logs. That way, we don't lose track of how models were trained.

**Comment by DrewGalbraith** [comment]
This is really already done via a .json file. It could be nice to have them in a yaml, but I'll close this for now as the goal is being reached.
